apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: myvol
          mountPath: /etc/conf
  volumes:
    - name: myvol
      configMap:
        name: mycm2  
