apiVersion: v1
kind: Pod
metadata:
  name: tom-pod
  labels:
    app: tom-app
spec:
  containers:
    - name: c2
      image: tomcat
      env:
        - name: HOST7
          valueFrom:
            configMapKeyRef:
              name: mycm1
              key: HOST
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mycm1
              key: PASS

