apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx-app1
spec:
  containers:
    - name: c1
      image: nginx:1.9.0
      volumeMounts:
        - name:  myvol
          mountPath: /etc/conf
      env:
        - name:  HOST7
          valueFrom:
            configMapKeyRef:
              name: mycm
              key: HOST
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mycm
              key: PASS
  volumes:
    - name: myvol
      configMap:
        name: mycm
